run:
  timeout: 5m
output:
  print-issued-lines: false
linters-settings:
  stylecheck:
    checks: [ "all" ]
  nlreturn:
    block-size: 1
  lll:
    line-length: 120
    tab-width: 1
linters:
  enable:
    - stylecheck
    - gci
    - nlreturn
    - lll
    - revive
    - typecheck